import type { Metadata } from 'next';
import './globals.css';
import type { ReactElement } from 'react';
import localFont from 'next/font/local';

import { Space_Grotesk, Inter } from 'next/font/google';
import ThemeProvider from '@/context/Theme';
import { cn } from "@/lib/utils";
import { Toaster } from '@/components/ui/sonner';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const interLocal = localFont({
  src: './fonts/Inter-Var.ttf',
  variable: '--font-inter',
  weight: '100 200 300 400 500 600 700 800 900',
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/site-logo.svg',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<ReactElement> {
  const session = await auth()
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", interLocal.className, spaceGrotesk.variable, "font-sans", inter.variable)}
      suppressHydrationWarning
    >
    <SessionProvider session={session}>
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          enableSystem
          defaultTheme="system"
          disableTransitionOnChange
        >
          {children}

        </ThemeProvider>
        <Toaster />
      </body>
    </SessionProvider>

    </html>
  );
}
