import type { Metadata } from 'next';
import './globals.css';
import type { ReactElement } from 'react';
import localFont from 'next/font/local';

import { Space_Grotesk } from 'next/font/google'

const interLocal = localFont({
  src: './fonts/Inter-Var.ttf',
  variable: '--font-inter',
  weight: '100 200 300 400 500 600 700 800 900',
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  weight: [ '300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/site-logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): ReactElement {
  return (
    <html
      lang="en"
      className={`${interLocal.className} ${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
